ALTER TABLE problems ADD COLUMN IF NOT EXISTS youtube_url VARCHAR(500);
ALTER TABLE problems ADD COLUMN IF NOT EXISTS video_title VARCHAR(255);

-- Add YouTube URLs for popular problems (NeetCode videos)
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=KLlXCFG5TnA', video_title = 'Two Sum - NeetCode' WHERE slug = 'two-sum';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=3OamzN90kPg', video_title = 'Contains Duplicate - NeetCode' WHERE slug = 'contains-duplicate';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=9UtInBqnCgA', video_title = 'Valid Anagram - NeetCode' WHERE slug = 'valid-anagram';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=vzdNOK2oB2E', video_title = 'Group Anagrams - NeetCode' WHERE slug = 'group-anagrams';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=YPTqKIgVk-k', video_title = 'Top K Frequent Elements - NeetCode' WHERE slug = 'top-k-frequent-elements';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=rYBtViXKMGk', video_title = 'Product of Array Except Self - NeetCode' WHERE slug = 'product-of-array-except-self';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=P6RZZMu_maU', video_title = 'Longest Consecutive Sequence - NeetCode' WHERE slug = 'longest-consecutive-sequence';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=1pkOgXD63yU', video_title = 'Best Time to Buy and Sell Stock - NeetCode' WHERE slug = 'best-time-to-buy-and-sell-stock';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=jgQjes7MgTM', video_title = 'Valid Palindrome - NeetCode' WHERE slug = 'valid-palindrome';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=kbwk1Tw3OhE', video_title = '3Sum - NeetCode' WHERE slug = '3sum';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=jzZsG8n2R9A', video_title = 'Container With Most Water - NeetCode' WHERE slug = 'container-with-most-water';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=ZnzvU03HtYk', video_title = 'Trapping Rain Water - NeetCode' WHERE slug = 'trapping-rain-water';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=aYBV0lMHzfQ', video_title = 'Valid Parentheses - NeetCode' WHERE slug = 'valid-parentheses';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=qkLl7nAwDPo', video_title = 'Min Stack - NeetCode' WHERE slug = 'min-stack';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=aaRv3ItDnRs', video_title = 'Binary Search - NeetCode' WHERE slug = 'binary-search';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=DjYZk8nrXVY', video_title = 'Reverse Linked List - NeetCode' WHERE slug = 'reverse-linked-list';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=XIdigk956u0', video_title = 'Merge Two Sorted Lists - NeetCode' WHERE slug = 'merge-two-sorted-lists';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=DqI3WOuOFbA', video_title = 'Linked List Cycle - NeetCode' WHERE slug = 'linked-list-cycle';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=6Xf5LfM-ciI', video_title = 'Invert Binary Tree - NeetCode' WHERE slug = 'invert-binary-tree';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=hTM3phVI6YQ', video_title = 'Maximum Depth of Binary Tree - NeetCode' WHERE slug = 'maximum-depth-of-binary-tree';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=OnSn2XEQ4MY', video_title = 'Same Tree - NeetCode' WHERE slug = 'same-tree';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=E36O5SWp-LE', video_title = 'Subtree of Another Tree - NeetCode' WHERE slug = 'subtree-of-another-tree';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=s6ATEkipzow', video_title = 'Validate BST - NeetCode' WHERE slug = 'validate-binary-search-tree';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=pAt6OR_FIjo', video_title = 'Number of Islands - NeetCode' WHERE slug = 'number-of-islands';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=EgI5nU9etnU', video_title = 'Clone Graph - NeetCode' WHERE slug = 'clone-graph';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=EgI5nU9etnU', video_title = 'Course Schedule - NeetCode' WHERE slug = 'course-schedule';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=Y0lT9Fck7qI', video_title = 'Climbing Stairs - NeetCode' WHERE slug = 'climbing-stairs';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=73r3KWiEvyk', video_title = 'House Robber - NeetCode' WHERE slug = 'house-robber';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=H9bfqBEtS6g', video_title = 'Coin Change - NeetCode' WHERE slug = 'coin-change';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=cjWnW0hdF1Y', video_title = 'Longest Increasing Subsequence - NeetCode' WHERE slug = 'longest-increasing-subsequence';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=Ua0GhsJSlWM', video_title = 'Word Break - NeetCode' WHERE slug = 'word-break';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=oaYk_MHIsxQ', video_title = 'Longest Common Subsequence - NeetCode' WHERE slug = 'longest-common-subsequence';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=mQhb6OFGbMo', video_title = 'Implement Trie - NeetCode' WHERE slug = 'implement-trie-prefix-tree';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=asbcE9mZz_U', video_title = 'Word Search - NeetCode' WHERE slug = 'word-search';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=GBKI9VSKdGg', video_title = 'Subsets - NeetCode' WHERE slug = 'subsets';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=s7AvT7cGdSo', video_title = 'Permutations - NeetCode' WHERE slug = 'permutations';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=9SgLBjXqwd4', video_title = 'Combination Sum - NeetCode' WHERE slug = 'combination-sum';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=q6IEA26hvXc', video_title = 'Merge K Sorted Lists - NeetCode' WHERE slug = 'merge-k-sorted-lists';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=oBt53YbR9Kk', video_title = 'Find Median from Data Stream - NeetCode' WHERE slug = 'find-median-from-data-stream';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=XEmy13g1Qxc', video_title = 'N-Queens - NeetCode' WHERE slug = 'n-queens';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=nXaxk27zwlk', video_title = 'Edit Distance - NeetCode' WHERE slug = 'edit-distance';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=Sx9NNgInc3A', video_title = 'LRU Cache - NeetCode' WHERE slug = 'lru-cache';
UPDATE problems SET youtube_url = 'https://www.youtube.com/watch?v=WNPBcap4jkU', video_title = 'Serialize and Deserialize Binary Tree - NeetCode' WHERE slug = 'serialize-and-deserialize-binary-tree';
